version: 2

############################################################################

references:
   default_environment_settings: &default_environment_settings
      docker:
        - image: circleci/openjdk:8-node
      environment:
        - ANT_OPTS: -Dzimbra.buildinfo.version=8.7.6_GA
        - BUILD: "/home/circleci"
      working_directory: /home/circleci/zm-mailbox
   default_attach_workspace: &default_attach_workspace
         attach_workspace:
            at: /home/circleci
   filter_branches: &filter_branches
     filters:
       branches:
         only:
           - develop
############################################################################

jobs:
  build:
    <<: *default_environment_settings
    steps:
      - checkout
      - run:
          name: Install ant-contrib
          command: sudo apt-get update; sudo apt-get install ant-contrib
      - run:
          name: Clone zm-timezones
          command: |
            cd "$BUILD"
            git clone https://github.com/Zimbra/zm-timezones.git -b develop --single-branch || exit 1
      - run:
          name: Running ant compile in native directory
          command: ant clean compile publish-local
          working_directory: native
      - run:
          name: Running ant compile in common directory
          command: ant clean compile publish-local
          working_directory: common
      - run:
          name: Running ant compile in soap directory
          command: ant clean compile publish-local
          working_directory: soap
      - run:
          name: Running ant compile in client directory
          command: ant clean compile publish-local
          working_directory: client
      - run:
          name: Running ant compile in store directory
          command: ant clean compile publish-local
          working_directory: store
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - zm-timezones
            - zm-mailbox
            - .ssh
            - .zcs-deps
  test:
    <<: *default_environment_settings
    steps:
      - *default_attach_workspace
      - run:
          name: Install junit-merge
          command: sudo npm config set strict-ssl false && sudo npm install -g junit-merge
      - run:
          name: Create test report directory to hold junit tests
          command: mkdir -p /tmp/junit/
      - run:
          name: Running ant test native
          command: ant test
          working_directory: native
      - run:
          name: Running ant test common
          command: ant test
          working_directory: common
      - run:
          name: Running ant test soap
          command: ant test
          working_directory: soap
      - run:
          name: Running ant test client
          command: ant test
          working_directory: client
      - run:
          name: Running ant test store
          command: ant test
          no_output_timeout: 1200s
          working_directory: store
      - run:
          name: Finding test results
          command: find . -type f -regex ".*/build/test/report/.*xml" | xargs junit-merge
      - run:
          name: Copy test results to proper directory
          command: cp merged-test-results.xml /tmp/junit/
      - store_test_results:
          path: /tmp/junit/
      - run:
         name: Deploy
         command: "echo deploy"
############################################################################

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          <<: *filter_branches
      - test:
          requires:
            - build
      - deploy:     
          type: approval 
          requires: 
            - test
          <<: *filter_branches
############################################################################
